export default {
  SET_STATE: "SET_STATE",

  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  INCREASE_ITEM: "INCREASE_ITEM",
  DECREASE_ITEM: "DECREASE_ITEM",
  CALCULATE_AMOUNT: "CALCULATE_AMOUNT",
  PLACE_ORDER_REQ: 'PLACE_ORDER_REQ',
  PLACE_ORDER_SUCCESS: 'PLACE_ORDER_SUCCESS',
  PLACE_ORDER_FAILURE: 'PLACE_ORDER_FAILURE',
}