export default {
    GET_ORDER_STATUS : 'GET_ORDER_STATUS',
    FAILED_TO_GET_ORDER_STATUS : 'FAILED_TO_GET_ORDER_STATUS',
    GET_PAYMENT_DETAILS: 'GET_PAYMENT_DETAILS',
    PAYMENT_DEATILS_LOADING_FAILED: 'PAYMENT_DEATILS_LOADING_FAILED'
  }