export default {
    GET_ORDER_STATUS_REQ : 'GET_ORDER_STATUS_REQ',
    GET_ORDER_STATUS_SUCCESS : 'GET_ORDER_STATUS_SUCCESS',
    FAILED_TO_GET_ORDER_STATUS : 'FAILED_TO_GET_ORDER_STATUS',
    GET_PAYMENT_DETAILS_REQ: 'GET_PAYMENT_DETAILS_REQ',
    GET_PAYMENT_DETAILS_SUCCESS: 'GET_PAYMENT_DETAILS_SUCCESS',
    PAYMENT_DEATILS_LOADING_FAILED: 'PAYMENT_DEATILS_LOADING_FAILED'

  }