export default {
  SET_STATE: "SET_STATE",

  LOAD_RESTAURENT_DETAILS_REQ: "LOAD_RESTAURENT_DETAILS_REQ",
  LOAD_RESTAURENT_DETAILS_SUCCESS: "LOAD_RESTAURENT_DETAILS_SUCCESS",
  LOAD_RESTAURENT_DETAILS_FAILURE: "LOAD_RESTAURENT_DETAILS_FAILURE",

  LOAD_ORDERS_REQ: "LOAD_ORDERS_REQ",
  LOAD_ORDERS_SUCCESS: "LOAD_ORDERS_SUCCESS",
  LOAD_ORDERS_FAILURE: "LOAD_ORDERS_FAILURE",

  LOAD_TRENDING_DISHES_REQ: "LOAD_TRENDING_DISHES_REQ",
  LOAD_TRENDING_DISHES_SUCCESS: "LOAD_TRENDING_DISHES_SUCCESS",
  LOAD_TRENDING_DISHES_FAILURE: "LOAD_TRENDING_DISHES_FAILURE",
  SEND_REQUEST_REQ: "SEND_REQUEST_REQ",
  SEND_REQUEST_SUCCESS: "SEND_REQUEST_SUCCESS",
  SEND_REQUEST_FAILURE: "SEND_REQUEST_FAILURE",

  SEND_TO_CART: "SEND_TO_CART",
  REMOVE_FROM_CART: "REMOVE_ITEM",
  GET_ORDER_STATUS_FAIL: 'GET_ORDER_STATUS_FAIL',
  GET_ORDER_STATUS_SUCCESS: 'GET_ORDER_STATUS_SUCCESS',

  GET_AMOUNT_FAIL: 'GET_AMOUNT_FAIL',
  GET_AMOUNT_SUCCESS: 'GET_AMOUNT_SUCCESS',
  LOAD_REQUEST_DATA_REQUEST:'LOAD_REQUEST_DATA_REQUEST',
  LOAD_REQUEST_DATA_SUCCESS:'LOAD_REQUEST_DATA_SUCCESS',
  LOAD_REQUEST_DATA_FAILURE:'LOAD_REQUEST_DATA_FAILURE',


}