export default {
  SET_STATE: "SET_STATE",
  SEND_PHONE_NO_REQ: 'SEND_PHONE_NO_REQ',
  SEND_PHONE_NO_SUCCESS: 'SEND_PHONE_NO_SUCCESS',
  SEND_PHONE_NO_FAILURE: 'SEND_PHONE_NO_FAILURE',

  CHECK_OTP_REQ: 'CHECK_OTP_REQ',
  CHECK_OTP_SUCCESS: 'CHECK_OTP_SUCCESS',
  CHECK_OTP_FAILURE: 'CHECK_OTP_FAILURE',
  
  SEND_NAME_REQ: 'SEND_NAME_REQ',
  SEND_NAME_SUCCESS: 'SEND_NAME_SUCCESS',
  SEND_NAME_FAILURE: 'SEND_NAME_FAILURE',

  GET_SESSION_DETAILS_REQ: 'GET_SESSION_DETAILS_REQ',
  GET_SESSION_DETAILS_SUCCESS: 'GET_SESSION_DETAILS_SUCCESS',
  GET_SESSION_DETAILS_FAILURE: 'GET_SESSION_DETAILS_FAILURE',

  RESEND_OTP_REQ: 'RESEND_OTP_REQ'
}