export default {
  // GET_SETTLEBILL_DEATILS: 'GET_SETTLEBILL_DEATILS',
  CHECKOUT_REQ: "CHECKOUT_REQ",
  CHECKOUT_SUCCESS: "CHECKOUT_SUCCESS",
  CHECKOUT_FAILURE: "CHECKOUT_FAILURE",
  SETTLE_BILL_REQ: "SETTLE_BILL_REQUEST",
  SETTLE_BILL_SUCCESS: "SETTLE_BILL_SUCCESS",
  SETTLE_BILL_FAILURE: "SETTLE_BILL_FAILURE",
}